name: activity_ring
description: "Library to create Progress bars in Apple Watch style rings.

This library is built with to be extremely customizable with low effort.
Please check the API documentation if you get stuck anywhere."
version: 0.1.0
homepage: https://github.com/akashgurava/activity_ring
repository: https://github.com/akashgurava/activity_ring

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
